stages:
  load_data:
    cmd: python pipelines/src/load_data.py ${data.image_folder_path} ${data.processed}
    deps:
      - pipelines/src/load_data.py
      - data/raw
      - pipelines/utils/transformers_setup.py
    outs:
      - ${data.processed}